### ISSUE TITLE
WeakMap and WeakSet are now a thing!

### ISSUE THREAD

**Issue by Sheraff** [AshleyScirra/via.js#3]
Hi ! 
I just stumbled upon your project, it looks cool. Never something I'll be allowed to use at work but definitely something I'd love to play with. Do you have any plans on updating it to use the new WeakMap and WeakSet objects? I see that you already reserved the space for it in WeakFactory and it doesn't seem too out there to implement! 
Cheers

**Comment by AshleyScirra** [comment]
What for? They don't help fix the memory management problem, only WeakRef does.
